//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanRepaymentApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoanRepaymentApp.LocalResources", typeof(LocalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ex. 5 or 5.3&quot;.
        /// </summary>
        internal static string AnnualInterestRateEx {
            get {
                return ResourceManager.GetString("AnnualInterestRateEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Interest Rate (%).
        /// </summary>
        internal static string AnnualInterestRateText {
            get {
                return ResourceManager.GetString("AnnualInterestRateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Repayment App.
        /// </summary>
        internal static string AppText {
            get {
                return ResourceManager.GetString("AppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string CalculateButtonText {
            get {
                return ResourceManager.GetString("CalculateButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Annual Interset Rate.
        /// </summary>
        internal static string EmptyAnnualInterestRate {
            get {
                return ResourceManager.GetString("EmptyAnnualInterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Loan Amount.
        /// </summary>
        internal static string EmptyLoanAmount {
            get {
                return ResourceManager.GetString("EmptyLoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Loan Period.
        /// </summary>
        internal static string EmptyLoanPeriod {
            get {
                return ResourceManager.GetString("EmptyLoanPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essential information is marked with an asterisk  .
        /// </summary>
        internal static string EssentialInfoText {
            get {
                return ResourceManager.GetString("EssentialInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string ExportToExcelText {
            get {
                return ResourceManager.GetString("ExportToExcelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Pdf.
        /// </summary>
        internal static string ExportToPdfText {
            get {
                return ResourceManager.GetString("ExportToPdfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterestAmountPaid.
        /// </summary>
        internal static string InterestAmountPaidLabel {
            get {
                return ResourceManager.GetString("InterestAmountPaidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Amount Paid.
        /// </summary>
        internal static string InterestAmountPaidText {
            get {
                return ResourceManager.GetString("InterestAmountPaidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Annual Interest Rate, please put numbers from 0 to 100.
        /// </summary>
        internal static string InvalidAnnualInterestRate {
            get {
                return ResourceManager.GetString("InvalidAnnualInterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Loan Amount, please put it in correct format.
        /// </summary>
        internal static string InvalidLoanAmount {
            get {
                return ResourceManager.GetString("InvalidLoanAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Loan Period, please put only integer numbers.
        /// </summary>
        internal static string InvalidLoanPeriod {
            get {
                return ResourceManager.GetString("InvalidLoanPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ex. 10,000.00&quot;.
        /// </summary>
        internal static string LoanAmountEx {
            get {
                return ResourceManager.GetString("LoanAmountEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Amount (£).
        /// </summary>
        internal static string LoanAmountText {
            get {
                return ResourceManager.GetString("LoanAmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Details.
        /// </summary>
        internal static string LoanDetailsFormText {
            get {
                return ResourceManager.GetString("LoanDetailsFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Row Main Loan Details.
        /// </summary>
        internal static string LoanDetailsFormTitle {
            get {
                return ResourceManager.GetString("LoanDetailsFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoanOutstandingBalance.
        /// </summary>
        internal static string LoanOutstandingBalanceLabel {
            get {
                return ResourceManager.GetString("LoanOutstandingBalanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Outstanding Balance.
        /// </summary>
        internal static string LoanOutstandingBalanceText {
            get {
                return ResourceManager.GetString("LoanOutstandingBalanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;ex. 5, 12, 36&quot;.
        /// </summary>
        internal static string LoanPeriodEx {
            get {
                return ResourceManager.GetString("LoanPeriodEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Period.
        /// </summary>
        internal static string LoanPeriodText {
            get {
                return ResourceManager.GetString("LoanPeriodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Period Type.
        /// </summary>
        internal static string LoanPeriodTypeText {
            get {
                return ResourceManager.GetString("LoanPeriodTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Main Details.
        /// </summary>
        internal static string MainDetailsText {
            get {
                return ResourceManager.GetString("MainDetailsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string MonthsText {
            get {
                return ResourceManager.GetString("MonthsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentAmount.
        /// </summary>
        internal static string PaymentAmountLabel {
            get {
                return ResourceManager.GetString("PaymentAmountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Amount.
        /// </summary>
        internal static string PaymentAmountText {
            get {
                return ResourceManager.GetString("PaymentAmountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentNo.
        /// </summary>
        internal static string PaymentNoLabel {
            get {
                return ResourceManager.GetString("PaymentNoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment No.
        /// </summary>
        internal static string PaymentNoText {
            get {
                return ResourceManager.GetString("PaymentNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrincipalAmountPaid.
        /// </summary>
        internal static string PrincipalAmountPaidLabel {
            get {
                return ResourceManager.GetString("PrincipalAmountPaidLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal Amount Paid.
        /// </summary>
        internal static string PrincipalAmountPaidText {
            get {
                return ResourceManager.GetString("PrincipalAmountPaidText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Amortization Schedule.
        /// </summary>
        internal static string ScheduleText {
            get {
                return ResourceManager.GetString("ScheduleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Insert the loan amount, the annual interest rate and the loan period..
        /// </summary>
        internal static string Step1Text {
            get {
                return ResourceManager.GetString("Step1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Press the button &quot;Calculate&quot;.
        /// </summary>
        internal static string Step2Text {
            get {
                return ResourceManager.GetString("Step2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error.
        /// </summary>
        internal static string UnexpectedErrorText {
            get {
                return ResourceManager.GetString("UnexpectedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Loan Repayment App.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string YearsText {
            get {
                return ResourceManager.GetString("YearsText", resourceCulture);
            }
        }
    }
}
